### ISSUE TITLE
io is not a function

### ISSUE THREAD

**Issue by SekibOmazic** [andbet39/Angular2SocketIO#1]
Hi there,

with `<script src="node_modules/socket.io/client/socket.io-1.4.5.js"></script>` in index.html I get following exception:

``` shell
TypeError: io is not a function
```

I've changed the src from above to:
`<script src="node_modules/socket.io-client/lib/index.js"></script>`
but the error message is still the same. 

Could you help?

**Comment by SekibOmazic** [comment]
OK,
it should be `<script src="node_modules/socket.io-client/socket.io.js"></script>`

Now I get:

``` shell
SyntaxError: Unexpected token <
```

in room.service.ts (loadRooms())

**Comment by andbet39** [comment]
Check in the RoomService.ts the url to the backend.

**Comment by SekibOmazic** [comment]
You mean `this.http.get('http://localhost:3000/api/rooms')`?

This URL is nowhere else defined, so it cannot work? Or am I missing something?

**Comment by andbet39** [comment]
I ve pushed a new version... try it

**Comment by SekibOmazic** [comment]
Thanks a lot!
